version: '3'

services:
  phagrancy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: phagrancy
    env_file: .env
    ports:
      - "80:8080"
#      - "443:8443"
    volumes:
      - "./boxes:/var/www/html/boxes"
